### ISSUE TITLE
Time Series exported through SpineDB_api doesn't show value

### ISSUE THREAD

**Issue by jimhommes** [spine-tools/Spine-Database-API#122]
Not sure if this should be posted here or at Spine-Toolbox. 

In a Spine-Toolbox project I have mapped a value as a Time Series and it's successfully imported to the SpineDB. When using the `export_data()` function in Python the time series shows up as an empty value:

`{..... 'object_parameter_values': [......, ('ldcNLDE-hourly', 'NL', 'Idc', , 'Import Init Data to DB@2021-03-18T13:06:21'), .....], .....}`

Since describing this whole setup is pretty detailed, I've included a project that I made from scratch:
[test.zip](https://github.com/Spine-project/Spine-Database-API/files/6167545/test.zip)

It's also not working for me when I try to switch to a Map or Array, but that's probably my misunderstanding.

**Comment by manuelma** [comment]
Very nice stuff @jimhommes 

I loaded your project and run the tool on the right. Works well for me, I get this at the output:

```
[('Sheet1', 'TestNumber', 'value', <spinedb_api.parameter_value.TimeSeriesVariableResolution object at 0x7f7bc49f9610>, 'Importer 1@2021-03-18T23:26:23')]
```

So you see, the forth element in that tuple is the time series parameter value. It is returned as a python object of type `spinedb_api.parameter_value.TimeSeriesVariableResolution`. That's the class we wrote to handle time series in toolbox. If you call `to_database()` on that object, you get the json representation that goes finally in the database. You can also access the attributes `indexes` and `values` to see the contents. Of course you can learn more by looking at `spinedb_api.parameter_value` module.

What is it that you're trying to do in the end? I'd be happy to help...

**Comment by jimhommes** [comment]
Thanks for the explanation! It seems that my Python installation prints empty strings as default instead of some `<spinedb_api.parameter_value.TimeSeriesVariableResolution object at 0x7f7bc49f9610>` that I was expecting. I just tried calling `to_database()` on the empty value, and it worked! It just printed
```
{"type": "time_series", "data": {"0001-01-01T00:00:00": 15.0, "0002-01-01T00:00:00": 30.0, "0003-01-01T00:00:00": 10.0, "0004-01-01T00:00:00": 27.0, "0005-01-01T00:00:00": 50.0}}
```

I'll try to figure out why my Python does this. Thanks for the help!

**Comment by manuelma** [comment]
Sounds good! I wonder if we'd need to implement something like `__repr__` for our parameter value classes. Please let us know if you figure something out.

**Comment by jimhommes** [comment]
One last addition to this: Python was not the problem. I had selected "Use Python interpreter" in Spine and this outputs the Python output in the Execution Log of the Tool. There it will show up as an empty value. Since my Python was printing objects as normal, I've selected the "Use Embedded Console" and it shows up in the Python console.

Including `__repr__` and `__str__` is always a nice to have I guess, but not necessary.

**Comment by manuelma** [comment]
I see it, it looks like our log is eating characters, will try to fix it. Thanks very much!

**Comment by soininen** [comment]
I the log interpeting `<` and `>` as some HTML tags? that would explain why that `<spinedb_api....>` stuff disappears.

**Comment by manuelma** [comment]
Yes @soininen , you're probably right.

**Comment by jkiviluo** [comment]
Must be an outdated issue.
