### ISSUE TITLE
Be careful not to hit "parser overflow error"

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Database-API#141]
Re https://github.com/Spine-project/Spine-Toolbox/issues/1527

Back in the referred issue we observed "parsed overflow error" when running exporter with scenario and tool filters. It looks like the query we were generating was too long. This may have many causes:

- to get data from the db, we basically create 'subqueries' that collect info from many different tables. For instance, we have the `object_class_sq` that selects from `object_class` and `entity_class`. Then we have the `wide_relationship_class_sq` that selects from some other tables *and* from the `object_class_sq` itself. It continues like this with `parameter_definition_sq` etc. So this is resulting in queries with a lot of nested `SELECT`s.
- To apply filters, we override some of the subqueries with more complex ones. For example, the tool filter overrides the `entity_sq` with another subquery that also selects from `parameter_value`, `tool`, `feature`, etc, so it becomes huge. Something similar can be said for the scenario filter that overrides the `parameter_value_sq`.
- The exporter works by creating a custom query that gets the stuff needed for the mapping. If one of the mappings is sending data to the 'table name', said query needs to be split across different 'table names', and thus needs to be filtered. We were doing this by nesting the entire query into another `SELECT`, just so we could reference columns by name in order to do the filtering. *We don't do this anymore* as we found a good alternative, and like this we 'solved' the issue referred above.

But, we don't seem immune to parser overflow error. It could happen in the future if for some reason we need to add more complexity to our queries.

So, the point of this issue is to rethink our design to try and make shorter queries.

CC @jkiviluo

**Comment by DillonJ** [comment]
The same model is working with the tool filter that was resulting in a TB on another machine. I'm not 100% sure if it's because I'm on another machine or it's due to the fix, but it looks promising. I will try asap on the machine where it failed originally.

**Comment by manuelma** [comment]
Thank you @DillonJ ! Please let me know it goes...

The above commit simplifies the tool-filtered-entity-query a lot. Before it was something like:

```sql
SELECT * FROM entity
WHERE id IN (
    SELECT id FROM (
        SELECT id, <filter_condition>
        FROM entity, <some_other_tables_needed_to_compute_the_filter_condition>
    )
    WHERE <filter_condition> IS TRUE
)
```

Now it is:

```sql
SELECT * FROM entity, <some_other_tables_needed_to_compute_the_filter_condition>
HAVING <filter_condition> IS TRUE
```

I had forgotten about `HAVING` when I first wrote the query.

**Comment by jkiviluo** [comment]
@manuelma  This is probably fixed by now. Re-open if you see need for that.
