### ISSUE TITLE
Backup db automatically before upgrade

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Database-API#166]
So every time we change the schema we need to tell everybody to backup their dbs. We can just do it automatically in sqlite and then just tell the user that a backup is available somewhere in their home folder.

**Comment by soininen** [comment]
How will this work with MySQL?

**Comment by soininen** [comment]
Also, backing up in user's home folder is a no-go for the FlexTool3 web-interface I'm currently working on. Is it possible to save the backups in the same folder as the original sqlite database with `.bak` extension or similar? That's what the web-interface is currently doing.

**Comment by manuelma** [comment]
> How will this work with MySQL?

We always backup as an sqlite file.

**Comment by DillonJ** [comment]
@soininen 
>Is it possible to save the backups in the same folder as the original sqlite database with .bak extension or similar? 

As a user, this would be the behaviour I would be expecting - seems reasonable

**Comment by jkiviluo** [comment]
@manuelma Was this implemented?

If not, I would actually prefer to have the prompt asking 'Backup and upgrade', 'Upgrade without backup' or 'Cancel'. That let's the user know there is a backup available and allows not to back up (e.g. when there is a big DB and you know it's all right to not backup).

**Comment by manuelma** [comment]
No, nothing done so far. Sounds like a good first issue.

**Comment by manuelma** [comment]
This was done in another issue.
