### ISSUE TITLE
More convenient API function for removing items

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Database-API#203]
It seems like we could do with more convenient methods for removing items. Right now, `revote_items()` and friends we need a list of object ids which aren't very convenient to obtain when working with a dataset in Pyton.

There may be issues I haven't considered, but for an API, removing items should be at the same level of convenience as adding and updating - it's a fundamental operation.

Edit: and maybe a companion function would be to get an entity ID from an entity name which could be a list if non-unique

**Comment by manuelma** [comment]
I completely agree, we need a full name-based add/update/remove API. At the moment the closest we have is the import_data which is a combination of add and update, not very predicable and of course it doesn't cover removal.

**Comment by soininen** [comment]
I agree. We should have a full-blown name-based add/update/remove API.

**Comment by jkiviluo** [comment]
Is this now done in v0.8?

**Comment by manuelma** [comment]
Needs polishing but it's on the works.

**Comment by jkiviluo** [comment]
I think we're there on this issue.
