### ISSUE TITLE
Add unit-tests for the DB server?

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Database-API#209]
We don't have many or any tests for this and we might want to keep using it in Mopo?

**Comment by soininen** [comment]
I believe adding tests is well worth it. We do *not* have definitive plans on replacing anything yet and *if* such time comes to pass it might be far in the future.

**Comment by jkiviluo** [comment]
Doesn't it also depend on whether we are thinking about doing risky changes to the current DB server? Don't need to be high risk. I mean if we are not, then we can push making those tests further down the road (or don't do them, if we do a rewrite in another language).

**Comment by soininen** [comment]
> Doesn't it also depend on whether we are thinking about doing risky changes to the current DB server?

Every change is risky as you might touch code that you think is unrelated but still breaks stuff somewhere else. Having at least the basic tests now would give us more confidence in our code.
