### ISSUE TITLE
Relationship object highlighting export mappings don't scale

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Database-API#244]
The query returned by `RelationshipObjectHighlightingMapping.filter_query()` doesn't scale and in fact hits a max query size limit when a relationship class contains enough relationships.

**Comment by manuelma** [comment]
This has been heavily refactored in that other branch about the entity... So if we fix this issue in master, I doubt we will be able to merge it into the entity branch later. So it might be a good idea to describe the fix in words here so we can apply in the entity branch??

**Comment by manuelma** [comment]
That said, I think there is an argument to be made about accepting to live with some bugs in 0.7 that do not bother much and we can fix in 0.8? What do you think?
