### ISSUE TITLE
Optimise purging

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Database-API#262]
> But also, maybe it is a mistake to implement purge_items based on remove_items, maybe purge should be its own operation? Like mark a table as purged in the cache, and then delete the entire contents of that table in the DB when committing. This would save enormous time eventually if the user purges a huge table. It is actually almost ridiculous to fetch all the rows just to say, okay, now remove them all.

_Originally posted by @manuelma in https://github.com/spine-tools/Spine-Database-API/issues/261#issuecomment-1707885146_

**Comment by manuelma** [comment]
I think the lazy purge is working just fine? Will close, new issues will come out naturally if bugs.
