### ISSUE TITLE
How to disambiguate multi-D entities with the same elements in a super class

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Database-API#304]
When building multi-D entities where the dimensions are specified via a superclass, it means one can select elements of any of the subclasses for those dimensions. This is nice.

But there is an issue regarding how to specify those elements. We have three alternatives but none of them seems to work so nicely:

1. By name (the current implementation) - this works because names are unique within the superclass, so no ambiguity. But in case the elements are themselves multi-D entities, it means one needs to start paying attention to the names of multi-D entities.
2. By (subclass name, element names) - this works because again that's a unique key, although it becomes quite verbose and seems to defeat the purpose of using a superclass. If I still need to specify the name of the subclass, then what's the point of having a superclass.
3. By element names - this might work in a lot of cases but not generally. The problematic case is where two entities have the same elements in two subclasses. One option would be to only ask the user to disambiguate (i.e., give the subclass name) in this particular case, and infer in all the other cases - this might be the nicest.

@jkiviluo @DillonJ what do you think? Any other ideas?

**Comment by jkiviluo** [comment]
Maybe 1. would actually work pretty well. E.g. a battery would need only one instance of `unit__node___unit__node`, so the issue would not be relevant in that case. Only when somebody wants to create the second `unit__node___unit__node` from the same entities, this becomes relevant. In that case unique constraint would be violated and we can warn the user and require the user to give a unique name. Since this should be extremely rare (and probably a mistake) it should be fine.

**Comment by manuelma** [comment]
Sorry @jkiviluo just to understand - in the case of `unit__node___unit__node`, option 1 means you need to give the names of the two `unit__node` relationships you want to link. This is what I showed on tuesday and it is how it's currently implemented. The feeling is, it would be better to give the names of `unit`, `node`, `unit`, `node` individually because that's what the user is most familiar with. That would be option 3 and it works except in those cases where the user has, e.g., a `unit__from_node` and a `unit__to_node` between the same `unit` and `node`.

So you're saying that maybe we should go with option 3 and ask for disambiguation only when it's needed, is that right?

**Comment by DillonJ** [comment]
Here we also need to keep in mind the copy paste functionality - although this is a DB_API issue, the implementation carries through directly to what the user sees in the DB. 

I think the solution needs to be robust and work in the general case and not designed based on a subjective view of what is a rare case, so it has to be 1 or 2. Right now a user can create a flow to and from a node relatively easy. It would not be nice to receive these warning messages when pasting in rows of data. I feel if we are to incur the high cost of changing things, it needs to be at least as good as what we have now.

With 1, the drawback is that to paste in data, a user has to construct the relationship name based on a knowledge of the convention db_api uses to create it in the first instance. This is not as nice as the system we have now. I feel like 2 is the least worst option.

Thinking through option 1 a little more - is there a way that copy/paste could be handled more nicely at tool box level? Perhaps toolbox could show the individual entities to allow for graceful copy/paste, but when creating these entities, they don't all need to be specified individually?

**Comment by jkiviluo** [comment]
> So you're saying that maybe we should go with option 3 and ask for disambiguation only when it's needed, is that right?

I wasn't probably saying that originally, but now, after working with the API for a while, I think that would be the best (#1 is bad, because you need to create the name). However, it means that we need to catch those corner cases and I don't know how hard that would be and whether it would cause speed losses. If that's hard, then we can just do #2 first and think about #1 later. When editing data programmatically, then it's probably best to use #2 anyway, because it should be faster (no need to lookup which class things belong to).

The GUI side is another question. There we want something that works nicely both in copy-paste and in self-editing.

**Comment by manuelma** [comment]
What do you think @soininen ?

**Comment by soininen** [comment]
I would go with 2 without blinking an eye. Class name + element names uniquely identify an entity, no matter how many dimensions it has. It will be a bother to guess how the names are generated (though nowadays you can use `helpers.name_from_elements()` but you still need the element names) so I do not think option 1 is the way to go. Having a dialogue with user as required by option 3 might work in the context of Toolbox but is tedious to implement and not nice when e.g. pasting stuff in large batches as @DillonJ pointed out.

Not sure why option 2 would "defeat the purpose of having a superclass". How we refer to the entities does not change the fact that it is the superclass that defines which entities can be used as elements.

**Comment by manuelma** [comment]
Thank you @soininen !

> Not sure why option 2 would "defeat the purpose of having a superclass"

The whole thing originates from SpineOpt. We have two 2-D classes, `unit__from_node` and `unit__to_node` where the dimensions are `unit` and `node`. We now want to create relationships between any two instances of these classes. Our first idea was to create the following four classes:
- `unit__from_node___unit__to_node`
- `unit__to_node___unit__from_node`
- `unit__from_node___unit__from_node`
- `unit__to_node___unit__to_node`

But that seemed awkward because the user would need to 'know' or 'remember' the dimension that would go in each position before creating the instance.

Therefore we introduced the superclass idea. We would create a `unit__node` superclass with subclasses `unit__from_node` and `unit__to_node`, and then `unit__node___unit__node` where the dimensions are (`unit__node`, `unit__node`). But now, if the user needs to provide the subclass as well as the element types when creating instances of `unit__node___unit__node`, we're kinda back at the situation where we had the four classes. The user needs to know the dimensions of each entity.

With the four classes, we wouldn't need to specify the subclass because it's fixed. So we kinda lose what we gained.

**Comment by soininen** [comment]
> The whole thing originates from SpineOpt...

Thanks for the explanation! I think I get what you are saying. I do not know how SpineOpt would exactly use these classes so I cannot say which approach would be more tedious in the end: single `unit__node__unit__node` with a superclass or four dimension-specific ones. Obviously, if you had more dimensions than two the latter would blow up in numbers and you would miss the superclass option :)

**Comment by jkiviluo** [comment]
> With the four classes, we wouldn't need to specify the dimension because it's fixed in the class definition. The element types would suffice.

Actually. In that example we would be adding entity to a specific entity_class. But so we would also have to do in the abstract class way - and that resolves the issue (there is no issue). We don't just add an entity to the DB - it's always an entity to a specific entity_class. (I can't just do `add_entity_item(name="foo")`, it has to be `add_entity_item(name="foo", entity_class_name="bar")`. 

However, in principle this could be possible for n-dimensional entities (assuming class-interpretation). But, if the entity names across the abstract class are unique, then it will be always clear what is being added (and therefore adding n-d entities could work without ambiguity even when no class information is provided). So, I think we just have to require unique name for abstract sub-class entities. We can provide an automatic name for the cases where this would happen (could be based on class name). In case of a battery in SpineOpt, I would recommend that the user would name these anyway in an understandable manner, e.g. charger and discharger. (In SpineOpt, we could also move to `node__to_unit` and `unit__to_node` so that it's clear from the start).

**Comment by jkiviluo** [comment]
Something I didn't say out loud above:
let's say we decide to use `unit__from_node___unit__to_node` as the class to hold the parameters for storage chargers. When you're inserting an entity to that class, you get the order of classes even if the entity byname would be "battery__west___battery__west".

**Comment by manuelma** [comment]
@jkiviluo not sure I follow.

The problem to me is adding an entity would look something like:

```python
add_entity_item(
    class_name="unit__node___unit__node",
    dimension_name_and_byname_list=(
        ("unit__from_node", ("car", "battery")), ("unit__to_node", ("car", "battery")
    )
)
```

which is kinda awful. Without the superclass approach we could have instead:

```python
add_entity_item(
    class_name="unit__from_node___unit__to_node", byname=("car", "battery", "car", "battery")
)
```

**Comment by jkiviluo** [comment]
But that latter one should work with superclass too. All the necessary information is there. The first car__battery needs to be member of the unit__from_node and the second car__battery should be a member of unit__to_node.

**Comment by manuelma** [comment]
Another difficulty is how awful it seems to look with import data:

```
import_data(
   db_map,
   entities=(("unit__node___unit__node", (("unit__from_node", ("car", "battery")), (("unit__to_node", ("car", "battery")))
)
```

Which means that to use the Importer, the user needs to provide a mapping for the dimension (subclass) names...

**Comment by manuelma** [comment]
I'm starting to think that a better option would be to just disallow two entites with the same elements in the same superclass (in the same way we disallow two entites with the same elements in the same *bottom* class).

And then in SpineOpt we'd just use `unit__to_node` and `node__to_unit`.

That would simplify the interface considerably I think. Because having to specify the subclass for each dimension really takes the API to a new level of complexity.

**Comment by DillonJ** [comment]
My feeling is that this the superclass idea adds a lot of complexity for not a lot of benefit.

**Comment by manuelma** [comment]
I have the same feeling - and to me that's an indication we're not doing it right. Class inheritance is supposed to be amazing to clarify things.

The inheritance of parameter definitions is clearly a benefit, at least in my opinion, because right now in SpineOpt we have a lot of repetition between `x__to_node` and `x__from_node` and that doesn't seem right.

But the multi-D entities with superclass dimensions needs more work I think. At API level, I really believe what I say in my last comment is the way to go. That means disallowing two multi-d entities with the same elements if they're in the same superclass. That just makes sense.

Then in SpineOpt we can decide if we want to use the superclass or not given its particular rules. My feeling is we'll still want to use it by introducing `node__to_unit` and `unit__to_node`, but we can discuss that separately.

**Comment by jkiviluo** [comment]
I tripped on my own feet above. So, I agree with your assessment @manuelma.

> That means disallowing two multi-d entities with the same elements if they're in the same superclass.

Here, I think we could just say that entity_classes, that are members of the same superclass, cannot have same elemental classes in the same order.

**Comment by manuelma** [comment]
> Here, I think we could just say that entity_classes, that are members of the same superclass, cannot have same elemental classes in the same order

That's another way of doing it indeed. Interesting.

**Comment by jkiviluo** [comment]
It should simplify the codebase, since the entity level would not need to be managed. It would also leave the door open to implementing that part if we ever would feel the need for it (using one of the not fully satisfactory choices).

**Comment by manuelma** [comment]
For now it seems simpler to just add the new unique key (superclass, element_name_list) for the entity since we already have  (class, element_name_list) - everything just seems to fall into place with this. But we can consider your suggestion later on @jkiviluo

**Comment by jkiviluo** [comment]
If it's already working in practice, then it sounds like a better idea as it allows bit more freedom for the user.

**Comment by manuelma** [comment]
Alright, will close now since it's all implemented the way we agreed above.
