### ISSUE TITLE
Importing existing entity renames the original

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Database-API#314]
Reimporting an existing multidimensional entity updates the original item. Executing

```
import_data(db_map, entities=(("relationship_class", ("object1", "object2")),)
```

creates an entity `object1__object2` as expected. However, executing the above statement again renames `object1__object2` to `object1__object2_1` which is unexpected.

Should the second import statement bail out without modifying the database mapping?

or

Should the second import statement add a new entity and keep the existing one?

**Comment by manuelma** [comment]
We can't add a new entity while keeping the existing one, it would violate the unique constraint on (class names, element name list). Option 1 is the way to go, will fix.
