### ISSUE TITLE
Base alternative can be purged

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Database-API#327]
Currently, we protect the 'Base' alternative: it cannot be removed from the database. However, when purging alternatives, also alternative id 1 (i.e. 'Base') gets purged.

This is a non-issue if we lift the protection as suggested in spine-tools/Spine-Toolbox#2331

**Comment by jkiviluo** [comment]
We shouldn't enforce a particular base alternative name. It's hard coding. For example, sometimes user may have two equal bases 'north' and 'south'. One adds a north part of the model and the other south part, but there is no common base. And I don't necessarily want to call my base 'Base', I might want to call it e.g. 'init'.

**Comment by soininen** [comment]
In case of removal, we actually protect the alternative id, not its name so we aren't hard-coding anything except the existence of at least one alternative. Anyway, this issue is not about whether we should have that guarantee but about a bug *if* we choose to keep the guarantee.

**Comment by jkiviluo** [comment]
I think this is to be discussed in the next Toolbox telco.

**Comment by soininen** [comment]
It was decided in the 2022-04-09 developer meeting that we will allow deletion of the 'Base' alternative.
