### ISSUE TITLE
Compatibility transformation should keep working after the first time

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Database-API#395]
When converting the default value of is_active parameter definitions to active_by_default for the entity class, we also set the default value to None. That means the second time the compatibility transformation is applied, active_by_default is going to be set to False regardless.

We should keep the is_active parameter definition with the original default value so compatibility transformations keep working forever - or at least until we know our users have learnt that they should use entity_alternative rather than is_active.

Will fix now.

**Comment by jkiviluo** [comment]
Looks like this is done - closing.
