### ISSUE TITLE
Type mismatch from Julia

### ISSUE THREAD

**Issue by hhoeschle** [spine-tools/Spine-Database-API#4]
Hey,

we call the spinedb_api from Julia in the following way:
```julia
@show id_list = [Int16(db_map.get_or_add_object_class(name=obj_class)[1]) for obj_class in object_classes]
@show typeof(id_list)
@show relationship_class = db_map.add_wide_relationship_class(name = relationship_name, object_class_id_list=id_list)
```

Unfortunately, when submitting the `id_list` to python it is translated in a `numpy.int64` rather than an `int`. This leads to the problem that the relationship is not correctly created, as the object_class_id in the sql-db is stored as BLOB.

Would it be possible to integrate the following explicit typecast:
```python
            for wide_kwargs in wide_kwargs_list:
                for dimension, object_class_id in enumerate(wide_kwargs["object_class_id_list"]):
                    narrow_kwargs = {
                        "id": id,
                        "dimension": dimension,
                        "object_class_id": int(object_class_id),
                        "name": wide_kwargs["name"],
                    }
                    item_list.append(narrow_kwargs)

```

I guess it may also occur at other places. I will collect and report them below.

Thanks
Hanspeter

[Link to file](https://github.com/Spine-project/Spine-Database-API/blob/master/spinedb_api/diff_database_mapping_add_mixin.py#L246)

**Comment by hhoeschle** [comment]
Also 
```
"object_id": int(object_id)
```

**Comment by manuelma** [comment]
perhaps we should cast all ids to int...

**Comment by manuelma** [comment]
perhaps we should cast all ids to int...

**Comment by manuelma** [comment]
perhaps we should cast all ids to int...

**Comment by manuelma** [comment]
Have you checked if [PyCall](https://github.com/JuliaPy/PyCall.jl) says anything about this ?

**Comment by hhoeschle** [comment]
The casting is done [here](https://github.com/JuliaPy/PyCall.jl/blob/master/src/conversions.jl#L16)

I guess somehow PyLong_FromLongLong maps onto numpy.int64 ... but it is hard to conclude

**Comment by jkiviluo** [comment]
Must be an outdated issue.
