### ISSUE TITLE
Mention the difference between entity_byname and element_name_list in documentation

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Database-API#411]
This seems to be a source of confusion.

**Comment by manuelma** [comment]
There is something here: https://spine-database-api.readthedocs.io/en/latest/db_mapping_schema.html#entity

**Comment by soininen** [comment]
We could add a few words about `entity_byname` in the DB mapping schema's introduction and tutorial as well. Point out that it consists of the 0-dimensional elements.
