### ISSUE TITLE
Support EPS Value in GDX Exporter

### ISSUE THREAD

**Issue by EWLCJahns** [spine-tools/Spine-Database-API#413]
Hello,

first of all thanks for the great work. I would like to make a suggestion for an improvement. Currently exporting "Inf" Values is supportet in the GDX exporter. Here is my suggestion to support "EPS" values as well:

In Line 23 of the file spine_db_api/spine_io/exporter/gdx_writer.py is a dictionary that translates math.inf to a GAMS "Inf value.

```
SPECIAL_CONVERSIONS = {EPS_VALUE: gdxcc.GMS_SV_EPS, math.inf: gdxcc.GMS_SV_PINF, -math.inf: gdxcc.GMS_SV_MINF}

```
We could add that a small value, for exmaple 1**-10 is translatet to EPS as well. 
```
SPECIAL_CONVERSIONS = {EPS_VALUE: gdxcc.GMS_SV_EPS, math.inf: gdxcc.GMS_SV_PINF, -math.inf: gdxcc.GMS_SV_MINF,  0.0000000001: gdxcc.GMS_SV_EPS}
```
The conversion from the string "EPS" to a Gams "EPS" would be more intuitive but would possibly require more changes.

**Comment by soininen** [comment]
"EPS" string also now converts to GAMS Eps.

**Comment by jkiviluo** [comment]
@EWLCJahns Thanks for the nice issue report - it was easy for Antti to implement.
