### ISSUE TITLE
Rename entity_class_display_mode and display_mode__entity_class tables

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Database-API#442]
entity_class_display_mode -> display_mode
display_mode__entity_class -> entity_class_display_mode

Also rename mapped items, import/export functions and such.

**Comment by soininen** [comment]
@jkiviluo @manuelma My conclusion of the discussion in #436 was that we want to keep `entity_class_display_mode` as is but remove the double underscore from `display_mode__entity_class`. Let me know if that conclusion was too hasty.

Anyway, now that I look at the names, `entity_class_display_mode` and `display_mode_entity_class`, I cannot but wonder if we will have lots and lots of confusion which is which. I would not mind if we came up with more distinctive names, like `entity_class_display_enum` and `entity_class_display_config`. What do you think?

**Comment by manuelma** [comment]
I agree we want to remove the double underscore. My suggestion is the following:

entity_class_display_mode -> display_mode
display_mode__entity_class -> entity_class_display_mode

Although the design is a bit confusing to me. At the moment, entity_class_display_mode is just a name and a description. display_mode__entity_class is a 'linking' table that associates a display mode with an entity class and then specifies some sort of display configuration, like colors, display status (?) and display order. So I don't know what's the point of the current entity_class_display_mode table if nothing is specified there other than name and description? @jkiviluo can you perhaps clarify?

**Comment by soininen** [comment]
> I agree we want to remove the double underscore. My suggestion was the following:
> entity_class_display_mode -> display_mode
> display_mode__entity_class -> entity_class_display_mode

We discussed this with @jkiviluo and ended up with the same naming scheme.

**Comment by soininen** [comment]
So the idea of the display_mode table is to provide a number of display modes that are selectable in e.g. DB editor. Once a display mode has been selected, the entity classes would be rendered using the colors, display order etc. specified for each class in entity_class_display_mode table.

**Comment by manuelma** [comment]
Thank you, but can we clarify the purpose of the current `entity_class_display_mode` table?

**Comment by manuelma** [comment]
> So the idea of the display_mode table is to provide a number of display modes that are selectable in e.g. DB editor. Once a display mode has been selected, the entity classes would be rendered using the colors, display order etc. specified for each class in entity_class_display_mode table.

Thank you! But the configuration (colors, display order) are not currently specified in entity_class_display_mode. They are specified in the linking table display_mode__entity_class. This means the same display mode can have different configurations depending on the class. So I don't get the purpose of creating those display modes if nothing is specified there other than the name (and the description). If the configuration was also specified with the display mode, then I would get why we would want to reuse them in different classes - well, the display_order couldn't be reused, but that would be a minor detail.

Anyways, perhaps we can talk it through in the next toolbox meeting? I feel I am missing something.

**Comment by soininen** [comment]
>This means the same display mode can have different configurations depending on the class.

This is exactly the point: `display_mode__entity_class` defines how each class behaves under each display mode. We do not want to e.g. color *all* class names red when certain display mode, say "highlight cats", is selected, we want to color *certain* classes only.

Anyway, we have plenty of opportunities to discuss this. The tables are not yet used anywhere so we can iron out the details without rush. I for one would like to know what 'display status' stands for :)

**Comment by manuelma** [comment]
That's what I was missing, perfect. Thanks very much for the explanation @soininen !

Then I think we can just go with that renaming we discussed? I have no other issues with this.

**Comment by soininen** [comment]
> Then I think we can just go with that renaming we discussed?

Great! I'll do the renaming soon as I would like to get a new Toolbox release out. Would be nice to have the migrations there.

**Comment by manuelma** [comment]
We also need to rename functions like import_entity_class__display_mode and so on - but probably you are already aware of this.
