### ISSUE TITLE
Drop gdxcc dependency

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Database-API#449]
The uses of `gdxcc` module should be replaced by `gams.core` which supersedes it. We used to get `gdxcc` as a third-party dependency from `gdx2py` but since `gdx2py=2.2.0` this is no longer the case.

**Comment by ptsavol** [comment]
I have a fix for this ready to go, if you're interested.

**Comment by soininen** [comment]
I accidentally pushed my fix (e022a81024ac972631c62afd77407bb6165b1243) to `master`.  @ptsavol Maybe you want to check if it looks alright?

**Comment by ptsavol** [comment]
Looks good to me. I'll remove my branch as it's now obsolete.

**Comment by soininen** [comment]
Alright, I think we are done here. Thanks a lot to everyone for the hard work!
